runners:
  default:
    cpu: [1]
    ram: [2]
    disk: default
    family: ["c7", "m7", "r7"]
    spot: lowest-price
    ssh: false
    tags:
      - 'TeamName:Data at Rest'
      - 'Environment:GitHub-Runners'
      - 'Customer:Cumulocity-IoT/cumulocity-clients-java-internal'