apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: "ci-registry-pull"
  containers:
    - name: "java"
      image: "registry.stage.c8y.io/public/zulu-openjdk-centos:17.0.16-jdk"
      command: ["/bin/sh"]
      args: ["-c", "cat"]
      tty: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      env:
        - name: HOME
          value: /home/jenkins/agent
        - name: JENKINS_URL
          value: http://jenkins.ci.svc.cluster.local:8080/
        - name: MAVEN_USER_HOME
          value: /home/jenkins/agent
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      workingDir: "/home/jenkins/agent"
      resources:
        requests:
          cpu: "3"
          memory: "8Gi"
        limits:
          cpu: "4"
          memory: "8Gi"

    - name: "docker"
      image: "registry.stage.c8y.io/ci/docker:20.10.17-dind"
      command: ["dockerd-entrypoint.sh"]
      args: []
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: true
        runAsUser: 0
        runAsGroup: 0
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "1Gi"

    - name: "helm"
      image: "registry.stage.c8y.io/ci/c8y-helm-charts:latest"
      command: ["/bin/bash"]
      args: ["-l", "-c", "cat"]
      tty: true
      resources:
        requests:
          cpu: "1"
          memory: "1024Mi"
        limits:
          cpu: "2"
          memory: "1024Mi"

    - name: "c8y-tools"
      image: "registry.stage.c8y.io/ci/c8y-smoke-provisioning:latest"
      command: ["/bin/sh"]
      args: ["-c", "cat"]
      tty: true
      resources:
        requests:
          cpu: "1"
          memory: "1024Mi"
        limits:
          cpu: "2"
          memory: "1024Mi"
